# Generated by Django 3.0.4 on 2020-04-05 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Laptops', 'Laptops'), ('Smartphones', 'Smartphones'), ('Cameras', 'Cameras'), ('Accessories', 'Accessories')], max_length=20)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('productnew', models.BooleanField(default=False)),
                ('image', models.ImageField(default='Images/no-image', upload_to='Images/')),
            ],
        ),
    ]
