# Generated by Django 3.0.4 on 2020-04-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_items_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Items')),
            ],
        ),
    ]
