# Generated by Django 3.0.4 on 2020-04-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cartitems_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(default=0, max_length=100, unique=False),
            preserve_default=False,
        ),
    ]
